[tool.poetry]
name = "simdesign"
version = "0.5.0"
description = "A collaborative framework for the simulated design of buildings following past and current seismic design procedures in Europe."
authors = ["Volkan Ozsarac <ozsarac.volkan@eucentre.it>"]
readme = "docs/README.md"
license = "AGPL-3.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU Affero General Public License v3 (AGPL-3.0)"
]
packages = [{ include = "simdesign" }]
keywords = ["earthquake", "seismic", "design", "simulation", "vulnerability"]

[tool.poetry.dependencies]
python = "~3.12"
scipy = "1.15.1"
pandas = "2.2.3"
pyarrow = "19.0.0"
openpyxl = "3.1.5"
"pyvista" = { version = "0.44.2", extras = ["all"] }
pydantic = "2.10.6"
openseespy = "3.7.1.2"
openseespywin = "3.7.1.2"

[tool.poetry.group.dev.dependencies]
flake8 = "7.0.0"
pytest = "8.3.4"
pytest-cov = "5.0.0"
pytest-env = "1.1.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"